title = "Solar Theme"
description = "A wizard is never late"

# The URL the site will be built for
base_url = "https://0xdkxy.github.io/solar-theme-zola"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
[markdown]
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_rss = true

[extra]
# Put all your custom variables here
site_menus = [
  { type = "title", name = "More About Me" },
  { type = "url", url = "https://github/hulufei.com/solar-theme-zola", name = "Repository" },
  { type = "url", url = "rss.xml", name = "RSS" },
  { type = "title", name = "Friends" },
  { type = "url", url = "https://github.com/0xdkxy/", name = "0xDkXy" },
]

solar_theme = "dark"
